<?php

$labels = array();
$labels['fetchmail'] = 'Récupérer le courrier';
$labels['fetchmaildelete'] = 'Effacer les emails après réception';
$labels['fetchmailenabled'] = 'Activer';
$labels['fetchmailfetchall'] = 'Récupérer tous les emails depuis le serveur';
$labels['fetchmailfolder'] = 'Dossier du serveur distant';
$labels['fetchmailkeep'] = 'Ne pas supprimer les messages sur le serveur';
$labels['fetchmailpollinterval'] = 'Intervalle d\'interrogation de la boite email';
$labels['fetchmailprotocol'] = 'Protocole';
$labels['fetchmailserver'] = 'Nom d\'hôte du serveur';
$labels['fetchmailusessl'] = 'Utiliser SSL';
$labels['fetchmail_entries'] = 'Comptes à récupérer depuis';
$labels['fetchmail_to'] = 'Récupérer les emails dans le compte de';
$labels['nofetch'] = 'Aucune entrée disponible';

$messages = array();
$messages['fetchmailabort'] = 'Annuler';
$messages['fetchmaildelconfirm'] = 'Voulez-vous supprimer cette entrée?';
$messages['fetchmaillimitreached'] = 'Limite atteinte';
$messages['fetchmailnewentry'] = 'Enregistrer comme nouveau';
$messages['opnotpermitted'] = 'Opération non autorisée!';
$messages['successfullydeleted'] = 'Supprimé avec succès!';
$messages['successfullydisabled'] = 'Désactivé avec succès!';
$messages['successfullyenabled'] = 'Activé avec succès!';
$messages['successfullysaved'] = 'Enregistré avec succès!';
$messages['textempty'] = 'Un ou plusieurs champs sont vides';
$messages['invaliddomain'] = 'Le domaine $s est invalide et/ou non résolvable via les DNS';
