<?php

$labels = array();
$labels['fetchmail'] = 'Pobierz Email';
$labels['fetchmaildelete'] = 'Usuń wiadomości po ich odebraniu';
$labels['fetchmailenabled'] = 'Aktywny';
$labels['fetchmailfetchall'] = 'Pobierz z serwera wszystkie wiadomości';
$labels['fetchmailfolder'] = 'Zdalny folder na serwerze';
$labels['fetchmailkeep'] = 'Nie usuwaj wiadomości z serwera';
$labels['fetchmailpollinterval'] = 'Interwał sprawdzania skrzynki e-mail';
$labels['fetchmailprotocol'] = 'Protokół';
$labels['fetchmailserver'] = 'Nazwa hosta serwera';
$labels['fetchmailusessl'] = 'Użyj SSL';
$labels['fetchmail_entries'] = 'Konta, z których pobierane są wiadomości';
$labels['fetchmail_to'] = 'Pobieraj wiadomości do';
$labels['nofetch'] = 'Brak dostępnych wpisów';

$messages = array();
$messages['fetchmailabort'] = 'Anuluj';
$messages['fetchmaildelconfirm'] = 'Czy na pewno chcesz usunąć ten wpis?';
$messages['fetchmaillimitreached'] = 'Osiągnięto limit';
$messages['fetchmailnewentry'] = 'Zapisz jako nowy';
$messages['opnotpermitted'] = 'Operacja nie dozwolona!';
$messages['successfullydeleted'] = 'Usunięto pomyślnie!';
$messages['successfullydisabled'] = 'Zdezaktywowano pomyślnie!';
$messages['successfullyenabled'] = 'Aktywowano pomyślnie!';
$messages['successfullysaved'] = 'Zapisano pomyślnie!';
$messages['textempty'] = 'Wymagane pola są puste';
$messages['invaliddomain'] = 'Nieprawidłowa domena $s, nie wykrywana w DNS';
